route_name:
  controller: ControllerClassName
  action: ActionName

home:
  controller: Taf\Controllers\PageController
  action: getHome

404:
  controller: Taf\Controllers\Error
  action: error404Action

userList:
  controller: Taf\Controllers\UserController
  action: userListAll